[tool.poetry]
name = "flaskan"
version = "0.1.0"
description = ""
authors = ["Jens Tinglev <tinglev@kth.se>"]

[tool.poetry.dependencies]
python = "3.7"
flask = "^1.1"
requests = "^2.22"
flask-jwt-extended = "^3.22"
flask_cors = "^3.0"

[tool.poetry.dev-dependencies]
pytest = "^3.4"